### ISSUE TITLE
Calipso fails to initiate the session when proxy-search request comes in

### ISSUE THREAD

**Issue by sashuk** [cliftonc/calipso#267]
Hello, hope that this will really help. I have Calipso working on my 80 port, so some guys constantly are bombing 80 port with proxy-search requests

```
GET http://www.baidu.com/ HTTP/1.1
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)
Content-Type: application/x-www-form-urlencoded
Accept: */*
Referer: http://www.baidu.com/
Host: www.baidu.com
Accept-Encoding: gzip, deflate
Proxy-Connection: Keep-Alive
```

The problem is that when these requests happen, following error crashes the Calipso

```
Cannot read property 'user' of undefined
TypeError: Cannot read property 'user' of undefined
    at PermissionFilter.check (C:\calipso\production\lib\core\Permission.js:183:27)
    at CalipsoMenu.addMenuItem (C:\calipso\production\lib\core\Menu.js:83:27)
    at Object.route (C:\calipso\production\modules\community\geothemes\geothemes.js:96:19)
    at routeModule (C:\calipso\production\lib\core\Module.js:133:15)
    at iterator (C:\calipso\production\lib\core\Module.js:54:5)
    at _asyncMap (C:\calipso\production\node_modules\async\lib\async.js:185:13)
    at async.forEach (C:\calipso\production\node_modules\async\lib\async.js:86:13)
    at Array.forEach (native)
    at _forEach (C:\calipso\production\node_modules\async\lib\async.js:26:24)
    at async.forEach (C:\calipso\production\node_modules\async\lib\async.js:85:9)

C:\calipso\production\node_modules\step\lib\step.js:39
        throw arguments[0];
                       ^
TypeError: Cannot read property 'user' of undefined
    at PermissionFilter.check (C:\calipso\production\lib\core\Permission.js:183:27)
    at CalipsoMenu.addMenuItem (C:\calipso\production\lib\core\Menu.js:83:27)
    at C:\calipso\production\lib\core\Module.js:145:24
    at Function.allMatched (C:\calipso\production\lib\core\Router.js:254:11)
    at next (C:\calipso\production\node_modules\step\lib\step.js:51:23)
    at next.parallel (C:\calipso\production\node_modules\step\lib\step.js:83:14)
    at check (C:\calipso\production\node_modules\step\lib\step.js:99:9)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

I've made a bit of research, and it appears that in the case of these requests object **_req.session**_ is not initialized, so the application crashes when tries to use it. So, I had to make a terrible, but working fix - in calipso.js, in routingFn() I've put this code:

``` javascript
    /*
    Fix for not-initialized session in Express - weird requests cause broken session,
    so everything that relies upon it - breaks as well.
    */
    if (!req.session) {
        console.log("Fake session insert");
        req.session = {
            cookie: { path: '/', _expires: '', originalMaxAge: '', httpOnly: true },
            user: {isAdmin: false},
            fake: true
        };
```

I understand that this is an issue of Express or Everyauth library, but maybe there is a known solution for Calipso.

And thanks for a Calipso CMS!

**Comment by richtera** [comment]
This seems to actually be a bug in express.session. If the URL doesn't start with / then session will not get defined at all. I added a wrapper to express.session to default the session to {} in that case.
I just pushed this to both branches.

**Comment by sashuk** [comment]
Great that finally figured that out.
